# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
